### ISSUE TITLE
Keyerror: 'entries"

### ISSUE THREAD

**Issue by Albireo6972** [whatdaybob/sonarr_youtubedl#42]
Hello, I am looking for some help with an issue I am having. I have grabbed this to try out, and am currently running it outside of Docker with Python. I am testing out a download from a playlist, and it sees the videos, but when it tries to download them (I assume) I get this error:

Traceback (most recent call last):
  File "C:\ProgramData\Sonarr_YouTubeDL\sonarr_youtubedl.py", line 587, in <module>
    main()
  File "C:\ProgramData\Sonarr_YouTubeDL\sonarr_youtubedl.py", line 581, in main
    client.download(series, episodes)
  File "C:\ProgramData\Sonarr_YouTubeDL\sonarr_youtubedl.py", line 473, in download
    logger.debug(f"    Extracted {len(playlist_dict['entries'])} entries")
KeyError: 'entries'

To clarify, I am running this on Windows Server 2019, with Python 3.10.7, and have pulled the code for the Dev build, installed all the items in "requirements.txt" and updated all python packages.

Any help would be appreciated, and if you need more info please let me know.

**Comment by Albireo6972** [comment]
Move to another project that worked.
