### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by Nammurg** [whatdaybob/sonarr_youtubedl#54]
Hello,

I have recently built and unraid server and installed this app as a docker container.
It is able to check with sonarr (running also in docker on the same network) for missing episodes but it gives me the below error messages...

Any ideas?

`ERROR: [youtube] Sz1kX1Z3CUE: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] sGPSkkeWl04: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] joS3xBGIKG4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] tvYRx82VmNY: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-04-04 21:28:01,327 - sonarr_youtubedl - ERROR - 'NoneType' object has no attribute 'get'
2023-04-04 21:28:01,327 - sonarr_youtubedl - ERROR - No video_url
2023-04-04 21:28:01,327 - sonarr_youtubedl - INFO -     1: Missing - Strange Delivery:
ERROR: [youtube] AQTX0Ep_hSk: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] zf1Nxm_Hd8g: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] qrBx4JzxP7Y: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] TtkJnxqELB0: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] M9z5lxKzfgY: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] CGquVxL-aFA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] ns5-xynWJtw: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] XYeiUo7HkjM: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-04-04 21:28:16,581 - sonarr_youtubedl - ERROR - 'NoneType' object has no attribute 'get'
2023-04-04 21:28:16,581 - sonarr_youtubedl - ERROR - No video_url
2023-04-04 21:28:16,582 - sonarr_youtubedl - INFO -     2: Missing - Halloween Special:
ERROR: [youtube] tQsrVyzxn9Y: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] nkbTsu5Zw_M: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] fdDd86Pysmw: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] 2UIRCCY02Ow: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] cCkNCsde_og: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

**Comment by maxi1134** [comment]
Ever found a solution?

**Comment by Nammurg** [comment]
> Ever found a solution?

No unfortunately, google search suggests that the yt-dl needs to be updated but I don't know how to do that...

**Comment by pdbintheusa** [comment]
I'm having the same issue.  After some research it seems as though my best guess is it's not properly handling when the Youtube owner account is using the new "youtube.com/@channelname" instead of old url style but I believe the solution is in the code itself for not handling the "@".

For clarification, I  am using the most up to date yt-dlp version.  I also am able to download a video directly through yt-dlp commands.  However, I get the same error as you when using sonarr_youtubedl.  So, it seems like it may be a mismatch between the handling of the "@" in the url for the channel that is causing the issue.  But I don't know for sure.

**Comment by Nammurg** [comment]
I have had this issue for a while now and have tested it with windows yt-dlp clients and I get the same exact error.
I have managed to successfully download a video using this version on windows: yt-dlp nightly 2023.09.21.222108 [Latest](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest)

**Comment by Nammurg** [comment]
Also I was successful downloading with version: yt-dlp 2023.07.06 [Latest](https://github.com/yt-dlp/yt-dlp/releases/latest)
I believe pull request #60 needs to be merged for this issue to be resolved.
@whatdaybob any chance this can me merged?

**Comment by Nammurg** [comment]
doing some more digging, I have managed to update the yt-dlp to the latest version of 2023.07.06 and I am still getting the same error.
However, when I run yt-dlp directly from the docker container, it works?!
I am not sure what is going on here :/

Result when running yt-dlp directly from the container:

`root@ce42168f54d6:/usr/local/bin# yt-dlp -P "/sonarr_root" "https://www.youtube.com/watch?v=Ghe058HpmMk" 
[youtube] Extracting URL: https://www.youtube.com/watch?v=Ghe058HpmMk
[youtube] Ghe058HpmMk: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] Ghe058HpmMk: Downloading ios player API JSON
[youtube] Ghe058HpmMk: Downloading android player API JSON
[youtube] Ghe058HpmMk: Downloading iframe API JS
[youtube] Ghe058HpmMk: Downloading player f130aa11
[youtube] Ghe058HpmMk: Downloading web player API JSON
[youtube] Ghe058HpmMk: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] Ghe058HpmMk: Downloading initial data API JSON
[info] Ghe058HpmMk: Downloading 1 format(s): 303+251
[download] Destination: /sonarr_root/Fix for youtube-dl Unable to extract uploader id [Ghe058HpmMk].f303.webm
[download] 100% of   11.59MiB in 00:00:11 at 1001.66KiB/s
[download] Destination: /sonarr_root/Fix for youtube-dl Unable to extract uploader id [Ghe058HpmMk].f251.webm
[download] 100% of    1.45MiB in 00:00:01 at 1.17MiB/s
[Merger] Merging formats into "/sonarr_root/Fix for youtube-dl Unable to extract uploader id [Ghe058HpmMk].webm"
Deleting original file /sonarr_root/Fix for youtube-dl Unable to extract uploader id [Ghe058HpmMk].f303.webm (pass -k to keep)
Deleting original file /sonarr_root/Fix for youtube-dl Unable to extract uploader id [Ghe058HpmMk].f251.webm (pass -k to keep)
root@ce42168f54d6:/usr/local/bin# `


Result when running sonarr-youtubedl as normal from the same docker container

`WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
ERROR: [youtube:tab] UCgJRL30YS6XFxq9Ga8W2J3A: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
Traceback (most recent call last):
  File "/app/sonarr_youtubedl.py", line 441, in <module>
    main()
  File "/app/sonarr_youtubedl.py", line 435, in main
    client.download(series, episodes)
  File "/app/sonarr_youtubedl.py", line 363, in download
    found, dlurl = self.ytsearch(ydleps, url)
  File "/app/sonarr_youtubedl.py", line 336, in ytsearch
    if 'entries' in result and len(result['entries']) > 0:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by SiraVista** [comment]
This error still persists...

It even fails with the first youtube channel in the example "config.yml.template" file: Smarter Every Day.

As a test I uncommented these two lines:
` # - title: Smarter Every Day`
`  #  url: https://www.youtube.com/channel/UC6107grRI4m0o2-emgoDnAA`

And I got loads of errors in the log file like this:
`2023-11-08 18:53:02,417 - sonarr_youtubedl - ERROR -       Failed - Helicopter Physics Series - #4 They're Gyroscopes - ERROR: [youtube] prRTWThrotU: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

Any one find an answer?  @whatdaybob , can you address this?

Thanks

**Comment by digitalrbnz** [comment]
Same issue here @whatdaybob Lets go

**Comment by darkf3n1x** [comment]
I have updated the container with the latest version. If you console into the container you can do 'pip install yt-dlp -U' to update to the latest yt-dlp release. 

However, I'm still receiving the following error
ERROR -       Failed - XPOGO Edition - ERROR: [youtube] CGOLDYiVqww: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by darkf3n1x** [comment]
Looks like this is an issue with yt-dlp https://github.com/yt-dlp/yt-dlp/issues/6247

The fix is to fully remove and re-add to the container
pip uninstall yt-dlp
pip install yt-dlp
