### ISSUE TITLE
unable to get this to run

### ISSUE THREAD

**Issue by Fespinoza831** [whatdaybob/sonarr_youtubedl#72]
2024-11-25 23:19:35,041 - sonarr_youtubedl - INFO - Initial run
2024-11-25 23:19:35,042 - sonarr_youtubedl - CRITICAL - Configuration file not found.
2024-11-25 23:19:35,048 - sonarr_youtubedl - CRITICAL - Create a config.yml using config.yml.template as an example.
2024-11-25 23:25:52,774 - sonarr_youtubedl - INFO - Initial run
2024-11-25 23:25:52,774 - sonarr_youtubedl - INFO - Configuration Found. Loading file.
2024-11-25 23:25:52,776 - sonarr_youtubedl - INFO - Scan interval set to every 1 minutes by config.yml
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/sonarr_youtubedl.py", line 441, in <module>
    main()
  File "/app/sonarr_youtubedl.py", line 433, in main
    series = client.filterseries()
  File "/app/sonarr_youtubedl.py", line 183, in filterseries
    series = self.get_series()
  File "/app/sonarr_youtubedl.py", line 118, in get_series
    return res.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-11-25 23:30:23,808 - sonarr_youtubedl - INFO - Initial run
2024-11-25 23:30:23,808 - sonarr_youtubedl - INFO - Configuration Found. Loading file.
2024-11-25 23:30:23,810 - sonarr_youtubedl - INFO - Scan interval set to every 1 minutes by config.yml
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/sonarr_youtubedl.py", line 441, in <module>
    main()
  File "/app/sonarr_youtubedl.py", line 433, in main
    series = client.filterseries()
  File "/app/sonarr_youtubedl.py", line 183, in filterseries
    series = self.get_series()
  File "/app/sonarr_youtubedl.py", line 118, in get_series
    return res.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-11-25 23:39:28,586 - sonarr_youtubedl - INFO - Initial run
2024-11-25 23:39:28,587 - sonarr_youtubedl - INFO - Configuration Found. Loading file.
2024-11-25 23:39:28,589 - sonarr_youtubedl - INFO - Scan interval set to every 1 minutes by config.yml
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/sonarr_youtubedl.py", line 441, in <module>
    main()
  File "/app/sonarr_youtubedl.py", line 433, in main
    series = client.filterseries()
  File "/app/sonarr_youtubedl.py", line 183, in filterseries
    series = self.get_series()
  File "/app/sonarr_youtubedl.py", line 118, in get_series
    return res.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

** Press ANY KEY to close this window **

**Comment by jaredcat** [comment]
`2024-11-25 23:19:35,042 - sonarr_youtubedl - CRITICAL - Configuration file not found.`
I'm going to guess that you never configured it to talk to Sonarr
